// <auto-generated />
using System;
using Fitness_Application.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fitness_Application.Migrations
{
    [DbContext(typeof(BDContext))]
    [Migration("20240505220557_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fitness_Application.Models.Cereri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idUtilizatorCerere")
                        .HasColumnType("int");

                    b.Property<int?>("idUtilizatorRaportat")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cereri", (string)null);
                });

            modelBuilder.Entity("Fitness_Application.Models.Meniu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("carboohidrati")
                        .HasColumnType("real");

                    b.Property<string>("descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("grasimi")
                        .HasColumnType("real");

                    b.Property<int>("idCreator")
                        .HasColumnType("int");

                    b.Property<int>("idProduseGramaje")
                        .HasColumnType("int");

                    b.Property<int>("idUtilizator")
                        .HasColumnType("int");

                    b.Property<float>("kcal")
                        .HasColumnType("real");

                    b.Property<float>("proteine")
                        .HasColumnType("real");

                    b.Property<float>("zahar")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Meniuri", (string)null);
                });

            modelBuilder.Entity("Fitness_Application.Models.Produs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("carbohidrati")
                        .HasColumnType("real");

                    b.Property<float?>("carbohidratiFiert")
                        .HasColumnType("real");

                    b.Property<float?>("carbohidratiPrajit")
                        .HasColumnType("real");

                    b.Property<int>("fiert")
                        .HasColumnType("int");

                    b.Property<float>("grasimi")
                        .HasColumnType("real");

                    b.Property<float?>("grasimiFiert")
                        .HasColumnType("real");

                    b.Property<float?>("grasimiPrajit")
                        .HasColumnType("real");

                    b.Property<byte[]>("imagine")
                        .HasColumnType("varbinary(max)");

                    b.Property<float>("kcal")
                        .HasColumnType("real");

                    b.Property<float?>("kcalFiert")
                        .HasColumnType("real");

                    b.Property<float?>("kcalPrajit")
                        .HasColumnType("real");

                    b.Property<int>("prajit")
                        .HasColumnType("int");

                    b.Property<float>("proteine")
                        .HasColumnType("real");

                    b.Property<float?>("proteineFiert")
                        .HasColumnType("real");

                    b.Property<float?>("proteinePrajit")
                        .HasColumnType("real");

                    b.Property<int?>("selectat")
                        .HasColumnType("int");

                    b.Property<float>("zahar")
                        .HasColumnType("real");

                    b.Property<float?>("zaharFiert")
                        .HasColumnType("real");

                    b.Property<float?>("zaharPrajit")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Produse", (string)null);
                });

            modelBuilder.Entity("Fitness_Application.Models.ProdusGramaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("crud")
                        .HasColumnType("int");

                    b.Property<int>("fiert")
                        .HasColumnType("int");

                    b.Property<float>("gramaj")
                        .HasColumnType("real");

                    b.Property<int>("idMeniu")
                        .HasColumnType("int");

                    b.Property<int>("idProdus")
                        .HasColumnType("int");

                    b.Property<int>("prajit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProdusGramaje", (string)null);
                });

            modelBuilder.Entity("Fitness_Application.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activ")
                        .HasColumnType("bit");

                    b.Property<string>("Activitate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Admin")
                        .HasColumnType("bit");

                    b.Property<int?>("Antrenor")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Greutate")
                        .HasColumnType("real");

                    b.Property<int?>("Inaltime")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Varsta")
                        .HasColumnType("int");

                    b.Property<float?>("antebrat")
                        .HasColumnType("real");

                    b.Property<float?>("coapsa")
                        .HasColumnType("real");

                    b.Property<float?>("gat")
                        .HasColumnType("real");

                    b.Property<float?>("greutateIdeala")
                        .HasColumnType("real");

                    b.Property<int?>("idAntrenor")
                        .HasColumnType("int");

                    b.Property<float?>("indiceMasaCorporala")
                        .HasColumnType("real");

                    b.Property<float?>("necesarCaloric")
                        .HasColumnType("real");

                    b.Property<float?>("procentDeGrasime")
                        .HasColumnType("real");

                    b.Property<string>("sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("talie")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
